name: C Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Compiler et tester
        run: |
          gcc cipher.c test.c -o test
          ./test
