name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile code
        run: gcc cipher.c main.c -o cipher

      - name: Run tests
        run: ./cipher

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Assure que le déploiement se fait après la compilation et les tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create deploy folder
        run: |
          mkdir -p deploy
          
      - name: Deploy compiled files
        run: |
          cp cipher deploy/
          cp main.c deploy/
          cp cipher.c deploy/

